=== NREL-Distribution-Suites/gdm-case-action/schema/distribution_system.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Name of the item."
      },
      "description": {
        "type": "string",
        "description": "A brief description of the item."
      },
      "contributor": {
        "type": "string",
        "description": "Name or identifier of the contributor."
      },
      "contributed_date": {
        "type": "string",
        "format": "date",
        "description": "Date when the item was contributed, in YYYY-MM-DD format."
      },
      "has_geo_coordinate": {
        "type": "boolean",
        "description": "Indicates whether the item has geographic coordinates."
      },
      "has_time_series_data": {
        "type": "boolean",
        "description": "Indicates whether the item contains time series data."
      },
      "has_split_phase": {
        "type": "boolean",
        "description": "Indicates whether the item is split-phase."
      }
    },
    "required": [
      "name",
      "description",
      "contributor",
      "contributed_date",
      "has_geo_coordinate",
      "has_time_series_data",
      "has_split_phase"
    ],
    "additionalProperties": false
  }

=== NREL-Distribution-Suites/gdm-case-action/catalogs/doc.json
{
    "name": "p5r",
    "description": "Equipment catalog for DistributionSystem models containes over 25000 models for BareConductorEquipment, CapacitorEquipment, ConcentricCableEquipment, DistributionTransformerEquipment, InverterEquipment and SolarEquipment",
    "contributor": "Aadil Latif",
    "contributed_date": "2024-12-04",
    "has_geo_coordinate": false,
    "has_time_series_data": false,
    "has_split_phase": true
}

=== NREL-Distribution-Suites/gdm-case-action/opendss/p5r/doc.json
{
    "name": "p5r",
    "description": "Slightly modified version of sub feeder within `P5R` region SMARTDS data from `SFO` area. Added PVsystem.",
    "contributor": "Kapil Duwadi",
    "contributed_date": "2024-12-03",
    "has_geo_coordinate": true,
    "has_time_series_data": true,
    "has_split_phase": true
}
